### PR TITLE
case-sensitive path check

### LINKED ISSUE #66: Server serves files wrongly on case insensitive filesystems
running on a case insensitive filesystem, the git-server serves files wrongly, if their path only differs in case.

for example:

```
http://localhost:${state.httpPort}/raw/owner1/repo1/master/readme.md
```

responds with the contents of the `README.md`,

but a similar request on github doesn't:

```
https://raw.githubusercontent.com/adobe/git-server/master/readme.md
```

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
fixes #66

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -52,8 +56,68 @@ function resolveRepositoryPath(options, owner, repo) {
...
+ * @param {string} pathToTest
+ */
+async function pathExists(parentDir, pathToTest) {
+  if (!await isCaseInsensitiveFS()) {
+    return fse.pathExists(path.join(parentDir, pathToTest));
+  }
+
+  let parent = parentDir;
+
+  const names = pathToTest.split('/').filter(el => el !== '');
```
Comment (tripodsan) [inline lib/utils.js]: does the `split('/')` work on windows?

Comment (filmaj) [reply lib/utils.js]: IMO better to use [`path.sep`](https://nodejs.org/api/path.html#path_path_sep)

Comment (stefan-guggisberg) [reply lib/utils.js]: @tripodsan @filmaj Initially I had `path.sep` but changed to `/`. `pathToTest` is taken from the url, hence it contains `/`.
